export const APP_CONFIG = {
  appName: 'ShowBookie',
  currency: 'INR',
  locale: 'en-IN',
  storageKeys: {
    db: 'showbookie.db',
    sessionUserId: 'showbookie.sessionUserId',
    bookingDraft: 'showbookie.bookingDraft',
    theme: 'showbookie.theme',
    locale: 'showbookie.locale',
    notificationsOpen: 'showbookie.notificationsOpen',
  },
  seatCapPerBooking: 6,
  booking: {
    convenienceFeePerSeat: 35,
    taxRate: 0.18,
    cancelWindowMinutes: 120,
  },
  payment: {
    retryLimit: 2,
    simulatedDelayMs: 900,
  },
  pagination: {
    moviesPerPage: 4,
  },
  supportedLocales: ['en', 'ta'],
  defaultLocale: 'en',
  defaultTheme: 'light',
  supportEmail: 'support@showbookie.com',
  supportPhone: '+91 124 488 5000',
  policies: {
    cancellationHours: 2,
  },
  promoCodes: {
    POPCORN10: {
      code: 'POPCORN10',
      type: 'percentage',
      value: 0.1,
      description: '10% off on movie subtotal up to Rs. 120',
      maxDiscount: 120,
    },
    DATE75: {
      code: 'DATE75',
      type: 'flat',
      value: 75,
      description: 'Flat Rs. 75 off on orders above Rs. 800',
      minSubtotal: 800,
    },
    FIRSTSHOW: {
      code: 'FIRSTSHOW',
      type: 'percentage',
      value: 0.15,
      description: '15% off for first booking',
      firstBookingOnly: true,
      maxDiscount: 150,
    },
  },
  paymentMethods: [
    { id: 'card', label: 'Card' },
    { id: 'upi', label: 'UPI' },
    { id: 'wallet', label: 'Wallet' },
  ],
  socialLinks: [
    { label: 'Instagram', href: '#' },
    { label: 'X', href: '#' },
    { label: 'YouTube', href: '#' },
  ],
  routeMap: {
    login: '/html/index.html',
    home: '/html/movie.html',
    movies: '/html/list.html',
    details: '/html/movdetails.html',
    seats: '/html/seats.html',
    checkout: '/html/payment.html',
    confirmation: '/html/booking.html',
    history: '/html/bookinghist.html',
    profile: '/html/profile.html',
    about: '/html/about.html',
    contact: '/html/contact.html',
    help: '/html/help.html',
    faq: '/html/faq.html',
    admin: '/html/admin.html',
    terms: '/html/terms.html',
    privacy: '/html/privacy.html',
    cancellation: '/html/cancellation.html',
  },
  legacyDetailMap: {
    django: '/html/movdetails.html',
    'dune-2': '/html/movdetails2.html',
    'shawshank-redemption': '/html/movdetails3.html',
    interstellar: '/html/movdetails4.html',
  },
};

function isoDateWithOffset(dayOffset, hour, minute) {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  date.setDate(date.getDate() + dayOffset);
  return date.toISOString();
}

export const SEED_DATA = {
  movies: [
    {
      id: 'mov_django',
      slug: 'django',
      legacyPath: '/html/movdetails.html',
      title: 'Django',
      language: 'English',
      certificate: 'A',
      genres: ['Western', 'Action', 'Drama'],
      durationMinutes: 165,
      rating: 8.9,
      votesLabel: '495 votes',
      releaseDate: '2025-08-02',
      popularityScore: 92,
      image: '/images/movie1.jpeg',
      heroImage: '/images/movie1.jpeg',
      synopsis:
        'A revenge-fuelled western where a freed bounty hunter rides into dangerous territory to rescue his wife.',
      cast: ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio'],
      tags: ['Recommended', 'Action-heavy'],
    },
    {
      id: 'mov_dune2',
      slug: 'dune-2',
      legacyPath: '/html/movdetails2.html',
      title: 'Dune: Part Two',
      language: 'English',
      certificate: 'UA13+',
      genres: ['Sci-Fi', 'Adventure', 'Drama'],
      durationMinutes: 166,
      rating: 8.3,
      votesLabel: '61.1K votes',
      releaseDate: '2025-09-15',
      popularityScore: 98,
      image: '/images/movie2.jpeg',
      heroImage: '/images/Dune Wallpaper.jpg',
      synopsis:
        'Paul Atreides unites with the Fremen while balancing prophecy, politics, and a war for Arrakis.',
      cast: ['Timothee Chalamet', 'Zendaya', 'Rebecca Ferguson'],
      tags: ['Blockbuster', 'IMAX'],
    },
    {
      id: 'mov_shawshank',
      slug: 'shawshank-redemption',
      legacyPath: '/html/movdetails3.html',
      title: 'The Shawshank Redemption',
      language: 'English',
      certificate: 'UA13+',
      genres: ['Drama'],
      durationMinutes: 142,
      rating: 9,
      votesLabel: '333 votes',
      releaseDate: '2025-06-10',
      popularityScore: 81,
      image: '/images/movie3.jpeg',
      heroImage: '/images/movie3.jpeg',
      synopsis:
        'An enduring prison drama about hope, friendship, and quiet resilience through decades behind bars.',
      cast: ['Tim Robbins', 'Morgan Freeman'],
      tags: ['Classic', 'Drama'],
    },
    {
      id: 'mov_interstellar',
      slug: 'interstellar',
      legacyPath: '/html/movdetails4.html',
      title: 'Interstellar',
      language: 'English',
      certificate: 'UA13+',
      genres: ['Sci-Fi', 'Adventure'],
      durationMinutes: 169,
      rating: 9,
      votesLabel: '3.3K votes',
      releaseDate: '2025-07-01',
      popularityScore: 94,
      image: '/images/movie4.jpeg',
      heroImage: '/images/movie4.jpeg',
      synopsis:
        'A pilot joins a mission through a wormhole to search for humanity’s next home while time slips away.',
      cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
      tags: ['Space epic', 'Fan favorite'],
    },
    {
      id: 'mov_midnight',
      slug: 'midnight-runner',
      legacyPath: '/html/movdetails.html?movie=midnight-runner',
      title: 'Midnight Runner',
      language: 'Tamil',
      certificate: 'UA',
      genres: ['Thriller', 'Crime'],
      durationMinutes: 138,
      rating: 7.8,
      votesLabel: '8.1K votes',
      releaseDate: '2025-10-05',
      popularityScore: 75,
      image: '/images/pexels-donaldtong94-109669.jpg',
      heroImage: '/images/pexels-donaldtong94-109669.jpg',
      synopsis:
        'A journalist chases a missing-person case that uncovers a dangerous chain of corruption across the city.',
      cast: ['Aarav K', 'Nivetha P'],
      tags: ['Tamil', 'Thriller'],
    },
    {
      id: 'mov_starlight',
      slug: 'starlight-echoes',
      legacyPath: '/html/movdetails.html?movie=starlight-echoes',
      title: 'Starlight Echoes',
      language: 'Hindi',
      certificate: 'U',
      genres: ['Romance', 'Musical', 'Drama'],
      durationMinutes: 124,
      rating: 7.4,
      votesLabel: '5.4K votes',
      releaseDate: '2025-05-20',
      popularityScore: 68,
      image: '/images/pexels-felipe-cardoso-861539-1764338.jpg',
      heroImage: '/images/pexels-felipe-cardoso-861539-1764338.jpg',
      synopsis:
        'Two musicians trying to break into the industry reconnect on a citywide concert tour.',
      cast: ['Meera Rao', 'Kabir Singh'],
      tags: ['Feel-good', 'Date night'],
    },
  ],
  theaters: [
    {
      id: 'theater_shenoy',
      name: 'PVR INOX Shenoy Nagar',
      city: 'Chennai',
      location: 'Shenoy Nagar',
      amenities: ['Dolby Atmos', 'Snacks', 'Wheelchair access'],
    },
    {
      id: 'theater_velachery',
      name: 'PVR Grand Mall Velachery',
      city: 'Chennai',
      location: 'Velachery',
      amenities: ['Recliners', 'Parking', 'Wheelchair access'],
    },
    {
      id: 'theater_adyar',
      name: 'PVR Ampa SkyOne',
      city: 'Chennai',
      location: 'Aminjikarai',
      amenities: ['Laser projection', 'Premium lounge'],
    },
  ],
  seatMaps: [
    {
      id: 'seatmap_standard',
      name: 'Main Hall Standard',
      sections: [
        { key: 'superstar', label: 'Superstar', price: 230, rows: ['A', 'B', 'C'], seatsPerRow: 12 },
        { key: 'platinum', label: 'Platinum', price: 190, rows: ['D', 'E', 'F', 'G'], seatsPerRow: 12 },
        { key: 'gold', label: 'Gold', price: 150, rows: ['H', 'I', 'J', 'K', 'L', 'M'], seatsPerRow: 12 },
      ],
    },
    {
      id: 'seatmap_luxe',
      name: 'Luxe Hall',
      sections: [
        { key: 'luxe', label: 'Luxe', price: 280, rows: ['A', 'B', 'C'], seatsPerRow: 10 },
        { key: 'premium', label: 'Premium', price: 210, rows: ['D', 'E', 'F', 'G'], seatsPerRow: 10 },
        { key: 'classic', label: 'Classic', price: 170, rows: ['H', 'I', 'J', 'K'], seatsPerRow: 10 },
      ],
    },
  ],
  shows: [
    {
      id: 'show_django_1',
      movieId: 'mov_django',
      theaterId: 'theater_shenoy',
      seatMapId: 'seatmap_standard',
      screenName: 'Screen 1',
      format: '2D',
      startTime: isoDateWithOffset(0, 13, 0),
      reservedSeats: ['A1', 'A2', 'D5', 'H4'],
    },
    {
      id: 'show_django_2',
      movieId: 'mov_django',
      theaterId: 'theater_velachery',
      seatMapId: 'seatmap_standard',
      screenName: 'Screen 3',
      format: '2D',
      startTime: isoDateWithOffset(1, 19, 0),
      reservedSeats: ['B7', 'B8', 'F4'],
    },
    {
      id: 'show_dune2_1',
      movieId: 'mov_dune2',
      theaterId: 'theater_shenoy',
      seatMapId: 'seatmap_luxe',
      screenName: 'IMAX',
      format: 'IMAX',
      startTime: isoDateWithOffset(0, 19, 0),
      reservedSeats: ['A1', 'A3', 'D2', 'D3', 'H1'],
    },
    {
      id: 'show_dune2_2',
      movieId: 'mov_dune2',
      theaterId: 'theater_adyar',
      seatMapId: 'seatmap_luxe',
      screenName: 'Luxe 4',
      format: '2D',
      startTime: isoDateWithOffset(2, 21, 30),
      reservedSeats: ['B4', 'B5', 'B6'],
    },
    {
      id: 'show_shawshank_1',
      movieId: 'mov_shawshank',
      theaterId: 'theater_velachery',
      seatMapId: 'seatmap_standard',
      screenName: 'Screen 2',
      format: '2D',
      startTime: isoDateWithOffset(0, 16, 10),
      reservedSeats: ['C3', 'C4', 'K7'],
    },
    {
      id: 'show_interstellar_1',
      movieId: 'mov_interstellar',
      theaterId: 'theater_adyar',
      seatMapId: 'seatmap_luxe',
      screenName: 'Luxe 2',
      format: '4K',
      startTime: isoDateWithOffset(1, 18, 45),
      reservedSeats: ['A8', 'E4', 'E5', 'J3'],
    },
    {
      id: 'show_midnight_1',
      movieId: 'mov_midnight',
      theaterId: 'theater_shenoy',
      seatMapId: 'seatmap_standard',
      screenName: 'Screen 4',
      format: '2D',
      startTime: isoDateWithOffset(2, 20, 10),
      reservedSeats: ['D1', 'D2', 'J11'],
    },
    {
      id: 'show_starlight_1',
      movieId: 'mov_starlight',
      theaterId: 'theater_velachery',
      seatMapId: 'seatmap_standard',
      screenName: 'Screen 5',
      format: '2D',
      startTime: isoDateWithOffset(1, 14, 20),
      reservedSeats: ['A9', 'E1', 'E2', 'I8'],
    },
  ],
  users: [
    {
      id: 'user_admin',
      name: 'Admin User',
      email: 'admin@showbookie.com',
      password: 'Admin@123',
      role: 'admin',
      phone: '+91 90000 12345',
      locale: 'en',
      createdAt: new Date().toISOString(),
      lastLoginAt: '',
      favorites: ['mov_dune2', 'mov_interstellar'],
      recentlyViewed: ['mov_dune2'],
      notifications: [],
      preferences: {
        theme: 'light',
      },
    },
    {
      id: 'user_demo',
      name: 'Demo Viewer',
      email: 'demo@showbookie.com',
      password: 'Demo@123',
      role: 'user',
      phone: '+91 98888 77777',
      locale: 'en',
      createdAt: new Date().toISOString(),
      lastLoginAt: '',
      favorites: ['mov_django'],
      recentlyViewed: ['mov_django', 'mov_interstellar'],
      notifications: [],
      preferences: {
        theme: 'light',
      },
    },
  ],
  bookings: [],
};
